kind: pipeline
type: kubernetes
name: twinsight-login-server
service_account: drone-runner

trigger:
  event:
  - tag
  
steps:
- name: Build Docker image
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/twinsight-login-server
    tags:
    - latest
    - ${DRONE_TAG}
    registry: docker-registry.k8s.array21.dev

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - twinsight-login-server
  when:
    status: [ failure ]

